name: Release Node.js Npm Package
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 14
          check-latest: true
          registry-url: https://registry.npmjs.org
          always-auth: true
          scope: '@gabictrlz' 
      - name: Install compile dependencies
        run: npm i
      - name: Install typescript
        run: npm i -g typescript
      - name: Compile library
        run: npm run build
      - name: Install dependencies
        run: npm uninstall && npm ci --ignore-scripts --production
      - name: Release
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release  